### ISSUE TITLE
Bug: uds_wp_pagination First and Last links go to homepage instead of current page

### ISSUE THREAD

**Issue by niclindh** [ASU-KE/UDS-WordPress-Theme#371]
In uds_wp_pagination (inc/navigation.php) the First and Last links go to

<?php echo get_home_url(); ?>/page/1/">First</a>

and 

<?php echo get_home_url(); ?>/page/<?php echo $GLOBALS['wp_query']->max_num_pages; ?>">Last

This breaks the first and last links on pages that are not the homepage, like on https://cronkite.asu.edu/cronkite-events/past-events/

**Comment by niclindh** [comment]
Dangit, GitHub swallowed the PHP.

Lines 78 and 92.

**Comment by niclindh** [comment]
Replacing get_home_url() with get_pagenum_link() seems to fix it. Also remove the slash in front of "page" to avoid a double-slash.

**Comment by zainabD** [comment]
I couldn't replicate this issue, even when I tried it on subpages and subsites under a multisite. 
@niclindh is this still an issue on cronkite?
Could you please test it by removing your fix from the child theme and updating the UDS theme to the latest version.

**Comment by niclindh** [comment]
I've disconnected my child theme, so I'm unable to do that. But if you've checked, I'm sure that bug got fixed!
