### ISSUE TITLE
Readme: Project Structure

### ISSUE THREAD

**Issue by wmcconnell** [ASU-KE/UDS-WordPress-Theme#48]
We _may_ need to edit, or delete, the current 'Project Structure' section of the readme. The current text was copied over from the Understrap project, and is intended to let developers know what might be different from a bog-standard WordPress plugin.

**Comment by nathan-rollins** [comment]
I added that Project Structure section. It needs to be updated, but it is nice to provide project developers with an overview of the project structure and what the main folders are for.
