### ISSUE TITLE
Required footer updates based on ASU site audit

### ISSUE THREAD

**Issue by cosmoonot** [ASU-KE/UDS-WordPress-Theme#508]
Kristin Gasser completed a site audit for the Cronkite School website, which identified the need for numerous link updates in the global footer.

1. "**Maps and Locations**" link in the footer should link to https://www.asu.edu/about/locations-maps.
2. "**Jobs**" link is https://asu.edu/asujobs which resolves to the correct URL of https://cfo.asu.edu/applicant.
3. "**Directory**" link should direct to https://isearch.asu.edu/asu-people/
4. "**Contact at ASU**" - "Again, the link resolves to the correct URL, but you may wish to update https://asu.edu/contactasu/ to https://www.asu.edu/about/contact"
5. Update **YouTube** and **Instagram** icons to the correct "square" versions.
6. Most of these use "shortcut" links in the footer resolve to the actual link, but according to the checklist, they should be set to the actual links: 

Copyright and Trademark (https://www.asu.edu/about/copyright-trademark/)
Accessibility (https://www.asu.edu/accessibility/)
Privacy (https://www.asu.edu/about/privacy/)
Terms of Use (https://www.asu.edu//about/terms-of-use/)
Emergency (https://cfo.asu.edu/emergency)

[AB#40178](https://asuteam404.visualstudio.com/3c3feac4-94b8-464c-8938-c46f8a83b297/_workitems/edit/40178)

**Comment by jkcox** [comment]
@cosmoonot will update links to match latest on asu.edu

> Update YouTube and Instagram icons to the correct "square" versions.

In the admin menu, check under Apperance > Menus, open your social media menu and you should be able to update icons to square version.

**Comment by jkcox** [comment]
Will be included in v1.3 release
